# ----
# Site

title: Kibramoa
description: Jekyll template for API documentation.
url: https://example.com
google_analytics_key:
permalink: pretty
baseurl:

# -----
# Build

timezone: Etc/UTC

collections:
  documentation:
    title: Overview
    position_number: 1
  cashier:
    title: CashierUI API Endpoints
    position_number: 2  
  api:
    title: Direct API Endpoints
    position_number: 3
  payins:
    title: Payins
    position_number: 4
  payouts:
    title: Payouts
    position_number: 5
  transaction-query:
    title: Transaction Query
    position_number: 6
  refunds:
    title: Refunds
    position_number: 7
  notifications:
    title: Notifications
    position_number: 8
  countries:
    title: GEOs and Methods
    position_number: 9
  datatables:
    title: Useful Data
    position_number: 10
  testdata:
    title: Testing Details
    position_number: 11
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENSE

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: "documentation"
    values:
      _hide_content: true
  - scope:
      type: "api"
    values:
      _hide_content: true

# -----------
# CloudCannon

types:
  - get
  - put
  - delete
  - post
  - patch

languages:
  bash: Bash
  c: C
  css: CSS
  html: HTML
  java: Java
  javascript: JavaScript
  json: JSON
  php: PHP
  python: Python
  ruby: Ruby

_options:
  content_markdown:
    format: p h4 h5 h6
    bold: true
    italic: true
    link: true
    bulletedlist: true
    numberedlist: true
    image: true
    table: true
    styles: /css/editor.css
